### ISSUE TITLE
Top left hamburger menu - Windowed bug

### ISSUE THREAD

**Issue by Calm-Poast** [Timvde/UserChrome-Tweaks#137]
Timvde/UserChrome-Tweaks/hamburger/move-to-top-left-Linux-Windows.css
Tested on Firefox 65.0.1 (64-bit) for Windows with default dark theme enabled.

The original emty space before the first tab reappears to the right of the newly moved hamburger menu only when windowed.

![bug example](https://user-images.githubusercontent.com/32389263/53430649-d62c4e80-39e6-11e9-8c35-20990e20dde6.png)

**Comment by Timvde** [comment]
Isn't that to be expected? Or did you also use some code to remove the space?

**Comment by Calm-Poast** [comment]
It was to be expected but I assumed that the space would be disabled inplace of the menu.
As for a new code this is what I've got:

_userChrome.css_
``
.titlebar-spacer[type="pre-tabs"] {
  display: none;
}
``

I marked the remaining drag space with a 1px white line starting from the menu icon's perimeter.

![windowed bug 137](https://user-images.githubusercontent.com/32389263/53806151-1f7b2180-3f44-11e9-8cd7-cfc2b5c4370f.png)
