### ISSUE TITLE
Problem with auto-hide.css

### ISSUE THREAD

**Issue by LOuroboros** [Timvde/UserChrome-Tweaks#152]
I checked this on Windows 7 Professional x64 and Windows 8.1 Professional x64 too.
If I use the code from **[auto-hide.css](https://github.com/Timvde/UserChrome-Tweaks/blob/master/toolbars/auto-hide.css)**, this is the result I get:
![1](https://user-images.githubusercontent.com/4485172/63983216-9704b600-ca7a-11e9-9b32-da2b8028646e.png)
That strange white bar that appears alongside the Google tab is actually a part of the webpage I'm visiting, Google.

If I modify it in the same way mentioned by @lokmeinmatz [**right here**](https://github.com/Timvde/UserChrome-Tweaks/issues/124#issuecomment-460190158), Firefox on Fullscreen does look correct, as you can see right below:
![2](https://user-images.githubusercontent.com/4485172/63983218-9b30d380-ca7a-11e9-975a-292c3f84caa9.png)
***Note**: I had to modify the amount of pixels from 7 to 5 for Firefox to look correct on my end.
I suppose that might depend on the user's desktop resolution? Mine's 1360x768, in case that matters.*

But then the problem becomes the Windowed mode, as you can see here, with a strange black bar showing up:
![3](https://user-images.githubusercontent.com/4485172/63983222-9e2bc400-ca7a-11e9-9901-2b2992dc1b87.png)

As a matter of fact, I noticed that on Windows 7 the issue is not present if you turn off Aero. Sadly, that is something you can't just do in Windows 8/10, because it breaks a lot of stuff.

**EDIT**: Oh yes, I am using Mozilla Firefox v68.0.2 x86, by the way.

**Comment by ana-ka** [comment]
Yep, I can confirm this and in fact noticed it some time ago. This particular issue appeared with FF67 I think.  Also it is present in 69 as well. Just didn't bother to report since this repo seems rather dead. :( There have been issues with auto-hide since a while. Sadly I have neither time nor skills to dig into this myself and it appears noone else has, too. Let's see what happens...

**Comment by simdimdim** [comment]
same issue popped up with me in 72 it was pretty much fine till 71, with x84_64 on arch

**Comment by sans-c** [comment]
Starting with the latest Firefox release 72.0, the location bar wont show up anymore. I had the problems described above earlier but it was still somewhat usable. In FF72 however, the location bar is gone for good. I'd appreciate any fixes/ideas, other than reverting to the default configuration.

If anyone needs any more information, let me know.
