### ISSUE TITLE
toolbars/auto-hide.css affected by Firefox 72 

### ISSUE THREAD

**Issue by pauricthelodger** [Timvde/UserChrome-Tweaks#157]
Hi there,

Updated to 72 this morning and noticed that something must have changed that affects auto-hide.

Display remains the same when selecting url bar via ctrl-L but flickers if you attempt to hover

![Example](https://user-images.githubusercontent.com/41227/71972131-faaaa700-3203-11ea-82e0-6344f13c17b3.png)

**Comment by sans-c** [comment]
See #152 for a possible solution and see if it works for you.

**Comment by pauricthelodger** [comment]
That works! Thanks for that, @sans-c =D

Will close this issue since that solves it for me though it might be worth throwing in a PR for your great and much less verbose fix? =)

**Comment by sans-c** [comment]
Created a PR for that. Please note that it is not my fix. Smart guys at reddit posted this. :) Also this version does not hide the bookmarks toolbar, whereas the previous version did. Still more usable than the old version I suppose.
