### ISSUE TITLE
auto-hide-sidebar.css seems to load 'behind' content as of Firefox 72(.01?)

### ISSUE THREAD

**Issue by ClefAria** [Timvde/UserChrome-Tweaks#159]
Originally, I thought it just stopped working, but then I noticed that the margin (10px by default) onto which you'd move your mouse to make the sidebar pop out would be visible while a new page was loading into a blank tab, but would be gone by the time the page loaded up. It seems almost as if the page loads on top of the sidebar, such that I can't bring it back to the foreground to be usable.

**Comment by boogiepop** [comment]
I have noticed this too, hopefully someone can find a workaround.

**Comment by Mipeli** [comment]
**OLD**

#sidebar-box {
  position: relative !important;
  overflow-x: hidden !important;
  margin-right: calc(var(--sidebar-hover-width) * -1) !important;
  left: var(--sidebar-hover-width) !important;
  min-width: var(--sidebar-hover-width) !important;
  max-width: var(--sidebar-hover-width) !important;
  border-right: 1px solid var(--sidebar-border-color);
}

**NEW**

#sidebar-box {
  position: relative !important;
  overflow-x: hidden !important;
  margin-right: calc(var(--sidebar-hover-width) * -1) !important;
  left: var(--sidebar-hover-width) !important;
  min-width: var(--sidebar-hover-width) !important;
  max-width: var(--sidebar-hover-width) !important;
  border-right: 1px solid var(--sidebar-border-color);
  z-index:2147483647 !important;
}

**Comment by ClefAria** [comment]
> 
> 
> **OLD**
> 
> #sidebar-box {
> position: relative !important;
> overflow-x: hidden !important;
> margin-right: calc(var(--sidebar-hover-width) * -1) !important;
> left: var(--sidebar-hover-width) !important;
> min-width: var(--sidebar-hover-width) !important;
> max-width: var(--sidebar-hover-width) !important;
> border-right: 1px solid var(--sidebar-border-color);
> }
> 
> **NEW**
> 
> #sidebar-box {
> position: relative !important;
> overflow-x: hidden !important;
> margin-right: calc(var(--sidebar-hover-width) * -1) !important;
> left: var(--sidebar-hover-width) !important;
> min-width: var(--sidebar-hover-width) !important;
> max-width: var(--sidebar-hover-width) !important;
> border-right: 1px solid var(--sidebar-border-color);
> z-index:2147483647 !important;
> }

This did the trick! Thanks so much!
