### ISSUE TITLE
auto-hide.css : navbar doesn't expand when focused using Ctrl-L

### ISSUE THREAD

**Issue by JadeSnail** [Timvde/UserChrome-Tweaks#165]
The latest auto-hide.css works well for me on nightly (thanks for that) except that it isn't expanded when focused using the keyboard shortcut (Ctrl-L).

**Comment by sans-c** [comment]
I have no idea whats going on..just out of curiousity, does F6 work for you? Also [Mozilla](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly) mentions Alt+D. Oh and by 

> it isn't expanded when focused 

do you mean that it actually receives focus and just does not expand? Sounds strange.

**Comment by JadeSnail** [comment]
Using both Alt+D and Ctrl+L, it receives focus (that is I can type in the field), but isn't expanded. The completions are expanded underneath. 

F6 does work. It focuses and expands it.
