### ISSUE TITLE
Firefox 75 broke some tweaks in my userChrome.css (tabbar)

### ISSUE THREAD

**Issue by ClarusAD** [Timvde/UserChrome-Tweaks#172]
With Firefox 75, how to hide tab bar (tabbar) when only one tab is open ?
It was working fine before

**Comment by ClarusAD** [comment]
SOLVED !

/* on mac feux tricolores */
#nav-bar { padding-left : 80px }

/* hide tab bar if only one tab */
tab:only-of-type { display:none !important }

#titlebar { margin-top:-28px }

/* set the height on the tabs instead */
tab {
	margin-top : 28px !important ;
	height : 28px ;/* ORI 32 */
	}

**Comment by Timvde** [comment]
That's not a style that's already in the repository, right? Could you make a pull request?

What does "on mac feux tricolores" mean?
