### ISSUE TITLE
Question about the behavior of "More Compact Tabs" on Windows 10 

### ISSUE THREAD

**Issue by LOuroboros** [Timvde/UserChrome-Tweaks#179]
I'm not entirely sure if this is a bug or if it's the intended behavior of the CSS, so I decided to bring up the matter just in case.
On Windows 10, by using [tabs/more-compact-tabs.css](https://github.com/Timvde/UserChrome-Tweaks/blob/master/tabs/more-compact-tabs.css) and that alone, the window of Firefox has this empty line above the tabs bar.
https://streamable.com/zzhkkw

It doesn't happen on Windows 8.1, as I use the same code there and "the issue" is not present.
I'm not sure if it'd be possible to "fix it" on Windows 10?

**Comment by LOuroboros** [comment]
I am still curious about this matter. Since the streamable video I uploaded was removed due to time expiration, I quickly recorded a new video.

https://user-images.githubusercontent.com/4485172/109268223-8527de80-77e9-11eb-9ad5-e637de2b1404.mp4

I'm not sure if this is relevant, but just in case, I use a screen resolution of 1360x768px.

**Comment by Timvde** [comment]
I don't actually know, I didn't write it, I just merged it :) I'll gladly accept a PR that improves the style.

**Comment by Glandos** [comment]
I updated this particular CSS, but unfortunately, I'm not a Windows user.

However, I tried to look on how to minimize the window decoration on Windows (there are really huge in height, and screen are huge in width, duh.). My findings were: none. You have to install a new theme, and it's not that easy.

In your example video, tabs are incorporated in the window decoration, so when the CSS reduces the tab height, it does nothing to the window decoration height because… it's not Firefox that draws it.

**Comment by LOuroboros** [comment]
> I updated this particular CSS, but unfortunately, I'm not a Windows user.
> 
> However, I tried to look on how to minimize the window decoration on Windows (there are really huge in height, and screen are huge in width, duh.). My findings were: none. You have to install a new theme, and it's not that easy.
> 
> In your example video, tabs are incorporated in the window decoration, so when the CSS reduces the tab height, it does nothing to the window decoration height because… it's not Firefox that draws it.

It's been about 16 months since I submitted this issue. At some point I looked around for other options.
Nowadays, I find myself using some of the snippets written by @MrOtherGuy mainly, and they actually work nicely.
It's been a while since I last had to touch my userChrome.css file.
Things are currently looking and working just as I want them to 👍 

https://user-images.githubusercontent.com/4485172/142743055-310a1b69-08be-4b9a-bbb3-fde3d13309d7.mp4

Since my question no longer matters, I think I can just safely close this Issue ticket, but if Timvde deems it necessary, they can always re-open it.

**Comment by Timvde** [comment]
Most of the styles here are written for pre-proton Firefox. I'm not maintaining it, and community contributions are rare. Maybe I better just archive the repository.
