### ISSUE TITLE
[Linux] auto-hide.css: content jerkiness

### ISSUE THREAD

**Issue by franglais125** [Timvde/UserChrome-Tweaks#43]
Thanks a lot for this excellent tweak. I'm already using it full-time.

This is to point out a minor issue. When the nav bar shows, the content is quickly shifted down by 1 or 2 pixels, and shifted back up after the nav bar is hidden. Here is a screen-cast of the problem:

https://i.imgur.com/jotJ0fb.mp4

This is on Debian stable.

Tagging @AlexVallat who proposed the PR.

**Comment by AlexVallat** [comment]
I'm afraid I can't reproduce that on Debian with Gnome, Hide Top Bar and Pixel Saver extensions active, Firefox Nightly with Compact density and default theme, maximised. Are you using any other userChrome.css tweaks? Or is there anything else you can think of that might affect the size of your navbar?

Other than that, the only thing I can suggest is to go to the last rule in the css and adjust the 1px value until it fixes the problem for your particular setup - just trial and error.

**Comment by franglais125** [comment]
> Are you using any other userChrome.css tweaks

@AlexVallat pff... For some reason I had a double copy of one of the rules, with the wrong height. Thanks for getting back to me, and sorry for the false alarm.
