### ISSUE TITLE
Navbar auto-hide.css not working on 58+

### ISSUE THREAD

**Issue by ouillepouille** [Timvde/UserChrome-Tweaks#78]
auto-hide.css doesn't work properly for some reason in 58+... 

i'm sad. tried fixed it but couldn't figure it out.

just letting you know !

**Comment by Timvde** [comment]
#67 has fixes for 58. It will also include autohiding the bookmarks toolbar. It makes sense to me. Do you agree with that? If you don't, I would certainly consider separating the bookmarks hiding in another file.

**Comment by ouillepouille** [comment]
Yes, great ! thanks !

2017-12-17 20:28 GMT-05:00 Tim Van den Eynde <notifications@github.com>:

**Comment by Timvde** [comment]
Merged now :)
